#!/bin/bash
set -e
# This code is the property of VitalPBX LLC Company
# License: Proprietary
# Date: 1-Agu-2023
# DRBD split-brain recovery
#
drbdadm secondary drbd0
drbdadm disconnect drbd0
drbdadm -- --discard-my-data connect drbd0
ssh root@$ip_slave "drbdadm connect drbd0"
echo "Disk Status"
drbdadm status
